/************************************************************************************
 *                                     set_2.c                                      *
 *                                                                                  *
 * Module housing solutions to problems 11-20                                       *
 ************************************************************************************/
/************************************************************************************
 *                             PREPROCESSOR DIRECTIVES                              *
 ************************************************************************************/
#include "sets.h"
#include "set_2.h"
/************************************************************************************
 *                               TOP LEVEL FUNCTIONS                                *
 ************************************************************************************/
/************************************************************************************
 *                                  - problem_12 -                                  *
 * 																																									*
 * The sequence of triangle numbers is generated by adding the natural numbers. So	*
 * the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten		*
 * terms would be:																																	*
 * 																																									*
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...																					*
 * 																																									*
 * Let us list the factors of the first seven triangle numbers:											*
 * 																																									*
 *  1: 1																																						*
 *  3: 1,3																																					*
 *  6: 1,2,3,6																																			*
 * 10: 1,2,5,10																																			*
 * 15: 1,3,5,15																																			*
 * 21: 1,3,7,21																																			*
 * 28: 1,2,4,7,14,28																																*
 * We can see that 28 is the first triangle number to have over five divisors.			*
 * 																																									*
 * What is the value of the first triangle number to have over five hundred					*
 * divisors? 																																				*
 ************************************************************************************/
void problem_12(void)
{
	const unsigned int N = 10; /* max number of iterations */

	unsigned int n;						 /* counter for calculating triangule number 'tri' */
	unsigned int tri;					 /* triangle number corresponding to counter 'n' */
	unsigned int num_divs;		 /* number of divisors for 'tri' */
	unsigned int smaller_div;  /* smaller of two divisors whose product is 'tri' */
	unsigned int min_big_div;  /* current smallest larger divisor */

  n   = 0;      /* zeroth counter */
  tri = 0;      /* zeroth triangle number */
  num_divs = 1; /* corresponds to 0 */ 

  while (num_divs < 500) {
    ++n;
    tri = tri + n;         /* calculate next triangle number */
		num_divs = 2;          /* corresponds to 1 and 'tri' */
    smaller_div = 1;
		min_big_div = tri;

    while (smaller_div <= min_big_div) {
      ++smaller_div;

      if (tri % smaller_div == 0) {
        min_big_div = tri / smaller_div;
        num_divs += 2;
      }
    }
	}

	printf("%u", tri);
}

const unsigned int DIG_MAT[100][50] = DIGITS;

void problem_13(void)
{
	printf("%u", DIG_MAT[50][30]);
}
